package com.vajasoft.nbextensions;

import java.io.File;
import javax.swing.JFileChooser;
import org.openide.util.NbPreferences;

final class VajasoftPanel extends javax.swing.JPanel {

    private final VajasoftOptionsPanelController controller;
    private final JFileChooser fileChooser = new JFileChooser();

    VajasoftPanel(VajasoftOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGitkLocation = new javax.swing.JLabel();
        fldGitkLocation = new javax.swing.JTextField();
        cmdBrowse = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(lblGitkLocation, org.openide.util.NbBundle.getMessage(VajasoftPanel.class, "VajasoftPanel.lblGitkLocation.text")); // NOI18N

        fldGitkLocation.setText(org.openide.util.NbBundle.getMessage(VajasoftPanel.class, "VajasoftPanel.fldGitkLocation.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(cmdBrowse, org.openide.util.NbBundle.getMessage(VajasoftPanel.class, "VajasoftPanel.cmdBrowse.text")); // NOI18N
        cmdBrowse.setMargin(new java.awt.Insets(2, 6, 2, 6));
        cmdBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGitkLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fldGitkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdBrowse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGitkLocation)
                    .addComponent(fldGitkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBrowse))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBrowseActionPerformed
        int ret = fileChooser.showOpenDialog(VajasoftPanel.this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            fldGitkLocation.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_cmdBrowseActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(VajasoftPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(VajasoftPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        fldGitkLocation.setText(NbPreferences.forModule(VajasoftPanel.class).get("gitkLocation", ""));
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(VajasoftPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(VajasoftPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        NbPreferences.forModule(VajasoftPanel.class).put("gitkLocation", fldGitkLocation.getText().trim());
    }

    boolean valid() {
        if (!fldGitkLocation.getText().isEmpty()) {
            File gitk = new File(fldGitkLocation.getText().trim() + "\\gitk.exe");
            return gitk.exists();
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBrowse;
    private javax.swing.JTextField fldGitkLocation;
    private javax.swing.JLabel lblGitkLocation;
    // End of variables declaration//GEN-END:variables
}
